
POLICY = "Policy"
PERSONALITY = "Personality"

POLICY_SCALE = {
    "Economy":          ["Communist", "Socialist", "Interventionist", "Indifferent", "Capitalist", "Free-Capitalist","Hyper-Capitalist"],
    "Liberty":          ["Totalitarian","Authoritarian","Centralized","Indifferent","Liberal","Libertarian","Anarchist"],
    "Class":            ["Under-Class", "Working-Class", "Populist", "Indifferent", "Middle-Class", "Aristocratic", "Plutocratic"],
    "Culture":          ["Reactionary", "Traditionalist", "Conservative", "Indifferent", "Progressive", "Accelerationist","Post-Culturalist"],
    "Diplomacy":        ["Supranationalist", "Globalist", "Diplomatic", "Indifferent", "Patriotic", "Nationalist", "Isolationist"],
    "Militancy":        ["Warhawk","Militarist","Forceful","Indifferent","Conflict-Averse","Nonviolent","Pacifist"],
    "Diversity":        ["Ethnocentrist","Homogenist","Preservationist","Indifferent","Pluralist","Multiculturalist","Inclusionist"],
    "Secularity":       ["Atheist", "Apostate", "Secularist", "Indifferent", "Religious", "Devout", "Fundamentalist"],
    "Technology":       ["Technophobic", "Luddite", "Hesitant", "Indifferent", "Modernist", "TechnoOptimist","Transhumanist"],
    "Legality":         ["Lawless","Arbitrary","Pragmatic","Indifferent","Regulatory","Proceduralist","Legalist"],
    "Justice":          ["Vengeful","Retributive","Punitive","Indifferent","Corrective","Rehabilitative","Abolitionist"],
    "Natural-Balance":  ["Eco-Absolutist","Ecologist","Conservationist","Indifferent","Utilitarian","Productivist","Industrialist"],
    "Government":       ["Popular-Democratic", "Democratic", "Repulican", "Indifferent", "Oligarchic", "Autocratic", "Dictatorial"],
}

PERSONALITY_SCALE = {
    "Aggreeableness": ["Hostile", "Unfriendly", "Aloof", "Neutral", "Friendly", "Agreeable", "Compassionate"],
    "Extroversion": ["Reclusive","Withdrawn","Quiet","Neutral","Sociable","Gregarious","Attention-Seeking"],
    "Conscientiousness": ["Negligent", "Careless", "Irresponsible", "Neutral", "Reliable", "Conscientious", "Perfectionist"],
    "Neuroticism": ["Cold", "Stable", "Calm", "Neutral", "Sensitive", "Anxious", "Fragile"],
    "Openness": ["Closed-Minded", "Conventional", "Traditional", "Neutral", "Inquisitive", "Investigative", "Obsessive"],

    "Loyalty": ["Rebellious", "Subversive", "Independent", "Indifferent", "Conformist", "Loyal", "Zealous"],
    "Ambition": ["Selfless", "Apathetic", "Unmotivated", "Steady", "Ambitious", "Selfish", "Messianic"],
    "Empathy": ["Sadistic", "Callous", "Apathetic", "Neutral", "Sympathetic", "Empathetic","Altrustic"],
    "Conscience": ["Immoral", "Amoral", "Rational", "Pragmatic", "Ethical", "Idealistic", "Virtuous"],
    "Trust": ["Paranoid", "Distrustful", "Skeptical", "Neutral", "Unsuspicious", "Trusting", "Gullible"],
    "Humor": ["Humorless", "Dry", "Reserved", "Neutral", "Witty", "Joker", "Clownish"],
    "Attachment": ["Avoidant", "Detached", "Reserved", "Neutral", "Affectionate", "Anxious", "Obsessive"],
        
    "Cognitive-Style": ["Concrete", "Practical", "Analytical", "Balanced", "Abstract", "Systems-Oriented", "Visionary"],
}

DERIVATIVES_SCALE = {
    "Corruptibility": ["+Ambition", "-Loyalty", "+Risk", "-Conscientiousness","-Class"],
    "Ideological-Rigidity": ["+Loyalty", "+Culture", "+Secularity", "-Curiosity", "-Adaptability","-Cognitive-Style"],
    "Leadership": ["+Assertiveness", "+Resilience", "-Emotionality", "+Cooperativeness", "+Social-Energy"],
    "Manipulativeness": ["-Attachment", "-Empathy", "+Ambition"],
    "Confidence": ["+Assertiveness", "+Resilience", "-Emotionality", "+Risk", "+Adaptability"],
    "Mercifulness": ["+Empathy", "+Justice", "-Ambition", "-Risk", "+Conscience"],
    "Cruelty": ["-Empathy", "-Justice", "+Ambition", "+Risk", "-Conscience"],
    
    "Risk": ["Risk-Averse", "Guarded", "Cautious", "Balanced", "Adventurous", "Daring", "Reckless"],
    
}

PRESET_POLICIES = {
    "Government":{
        "Economy":          ["Communist", "Socialist", "Indifferent", "Capitalist", "Free-Capitalist"],
        "Liberty":          ["Authoritarian", "Statist", "Indifferent", "Libertarian", "Anarchist"],
        "Class":            ["Lower-Class", "Working-Class", "Populist", "Indifferent", "Middle-Class", "Aristocratic", "Plutocratic"],
        "Technology":       ["Technophobic", "Ludditeive", "Hesitant", "Indifferent", "Modernist", "TechnoOptimist","Transhumanist"],
        "Legality":         ["Arbitrarian", "Pragmatic", "Indifferent", "Proceduralist", "Legalist"],
        "Culture":          ["Traditionalist", "Conservative", "Indifferent", "Progressive", "Accelerationist"],
        "Diplomacy":        ["Globalist", "Diplomatic", "Indifferent", "Patriotic", "Nationalist"],
        "Militancy":        ["Militarist", "Strategic", "Indifferent", "Diplomatic", "Pacifist"],
        "Diversity":        ["Homogenous", "Preservationist", "Indifferent", "Heterogeneous", "Multiculturalist"],
        "Secularity":       ["Apostate", "Secularist", "Indifferent", "Religious", "Devout"],
        "Justice":          ["Retributionist", "Punitive", "Indifferent", "Correctivist", "Rehabilitative"],
        "Natural-Balance":  ["Ecologist", "Naturalist", "Indifferent", "Productivist", "Industrialist"],
        "Government":       ["Democratic", "Republican", "Indifferent", "Oligarchic", "Autocratic"]
    },
    "Military":{
        "Economy":          ["Communist", "Socialist", "Indifferent", "Capitalist", "Free-Capitalist"],
        "Liberty":          ["Authoritarian"],
        "Class":           ["Lower-Class", "Working-Class", "Populist", "Indifferent", "Middle-Class", "Aristocratic", "Plutocratic"],
        "Technology":       ["Technophobic", "Luddite", "Hesitant", "Indifferent", "Modernist", "TechnoOptimist","Transhumanist"],
        "Legality":         ["Arbitrarian", "Pragmatic", "Indifferent", "Proceduralist", "Legalist"],
        "Culture":          ["Traditionalist", "Conservative", "Indifferent", "Progressive", "Accelerationist"],
        "Diplomacy":        ["Globalist", "Diplomatic", "Indifferent", "Patriotic", "Nationalist"],
        "Militancy":        ["Militarist", "Strategic"],
        "Diversity":        ["Homogenous", "Preservationist", "Indifferent", "Heterogeneous", "Multiculturalist"],
        "Secularity":       ["Apostate", "Secularist", "Indifferent", "Religious", "Devout"],
        "Justice":          ["Retributionist", "Punitive", "Indifferent", "Correctivist", "Rehabilitative"],
        "Natural-Balance":  ["Indifferent", "Productivist", "Industrialist"],
        "Government":       ["Democratic", "Republican", "Indifferent", "Oligarchic", "Autocratic"]
    },
    "Intelligence":{
        "Economy":          ["Communist", "Socialist", "Indifferent", "Capitalist", "Free-Capitalist"],
        "Liberty":          ["Authoritarian", "Statist"],
        "Class":            ["Lower-Class", "Working-Class", "Populist", "Indifferent", "Middle-Class", "Aristocratic", "Plutocratic"],
        "Technology":       ["Technophobic", "Luddite", "Hesitant", "Indifferent", "Modernist", "TechnoOptimist","Transhumanist"],
        "Legality":         ["Arbitrarian", "Pragmatic", "Indifferent", "Proceduralist", "Legalist"],
        "Culture":          ["Traditionalist", "Conservative", "Indifferent", "Progressive", "Accelerationist"],
        "Diplomacy":        ["Globalist", "Diplomatic", "Indifferent", "Patriotic", "Nationalist"],
        "Militancy":        ["Militarist", "Strategic", "Indifferent", "Diplomatic", "Pacifist"],
        "Diversity":        ["Homogenous", "Preservationist", "Indifferent", "Heterogeneous", "Multiculturalist"],
        "Secularity":       ["Apostate", "Secularist", "Indifferent", "Religious", "Devout"],
        "Justice":          ["Retributionist", "Punitive", "Indifferent", "Correctivist", "Rehabilitative"],
        "Natural-Balance":  ["Ecologist", "Naturalist", "Indifferent", "Productivist", "Industrialist"],
        "Government":       ["Democratic", "Republican", "Indifferent", "Oligarchic", "Autocratic"]
    },
    "Religious":{
        "Economy":          ["Communist", "Socialist", "Indifferent", "Capitalist", "Free-Capitalist"],
        "Liberty":          ["Authoritarian", "Statist", "Indifferent", "Libertarian", "Anarchist"],
        "Class":            ["Lower-Class", "Working-Class", "Populist", "Indifferent", "Middle-Class", "Aristocratic", "Plutocratic"],
        "Technology":       ["Technophobic", "Luddite", "Hesitant", "Indifferent", "Modernist", "TechnoOptimist","Transhumanist"],
        "Legality":         ["Arbitrarian", "Pragmatic", "Indifferent", "Proceduralist", "Legalist"],
        "Culture":          ["Traditionalist", "Conservative", "Indifferent", "Progressive", "Accelerationist"],
        "Diplomacy":        ["Globalist", "Diplomatic", "Indifferent", "Patriotic", "Nationalist"],
        "Militancy":        ["Militarist", "Strategic", "Indifferent", "Diplomatic", "Pacifist"],
        "Diversity":        ["Homogenous", "Preservationist", "Indifferent", "Heterogeneous", "Multiculturalist"],
        "Secularity":       ["Religious", "Devout"],
        "Justice":          ["Retributionist", "Punitive", "Indifferent", "Correctivist", "Rehabilitative"],
        "Natural-Balance":  ["Ecologist", "Naturalist", "Indifferent", "Productivist", "Industrialist"],
        "Government":       ["Democratic", "Republican", "Indifferent", "Oligarchic", "Autocratic"]
    },
    "Company":{
        "Economy":          ["Socialist", "Indifferent", "Capitalist", "Free-Capitalist"],
        "Liberty":          ["Authoritarian", "Statist", "Indifferent", "Libertarian", "Anarchist"],
        "Class":            ["Lower-Class", "Working-Class", "Populist", "Indifferent", "Middle-Class", "Aristocratic", "Plutocratic"],
        "Technology":       ["Technophobic", "Luddite", "Hesitant", "Indifferent", "Modernist", "TechnoOptimist","Transhumanist"],
        "Legality":         ["Arbitrarian", "Pragmatic", "Indifferent", "Proceduralist", "Legalist"],
        "Culture":          ["Traditionalist", "Conservative", "Indifferent", "Progressive", "Accelerationist"],
        "Diplomacy":        ["Globalist", "Diplomatic", "Indifferent", "Patriotic", "Nationalist"],
        "Militancy":        ["Militarist", "Strategic", "Indifferent", "Diplomatic", "Pacifist"],
        "Diversity":        ["Homogenous", "Preservationist", "Indifferent", "Heterogeneous", "Multiculturalist"],
        "Secularity":       ["Apostate", "Secularist", "Indifferent", "Religious", "Devout"],
        "Justice":          ["Retributionist", "Punitive", "Indifferent", "Correctivist", "Rehabilitative"],
        "Natural-Balance":  ["Ecologist", "Naturalist", "Indifferent", "Productivist", "Industrialist"],
        "Government":       ["Democratic", "Republican", "Indifferent", "Oligarchic", "Autocratic"]
    },
    "Mercenaries":{
        "Economy":          ["Indifferent", "Capitalist", "Free-Capitalist"],
        "Liberty":          ["Authoritarian", "Statist", "Indifferent", "Libertarian", "Anarchist"],
        "Class":            ["Lower-Class", "Working-Class", "Populist", "Indifferent", "Middle-Class", "Aristocratic", "Plutocratic"],
        "Technology":       ["Technophobic", "Luddite", "Hesitant", "Indifferent", "Modernist", "TechnoOptimist","Transhumanist"],
        "Legality":         ["Arbitrarian", "Pragmatic", "Indifferent", "Proceduralist", "Legalist"],
        "Culture":          ["Traditionalist", "Conservative", "Indifferent", "Progressive", "Accelerationist"],
        "Diplomacy":        ["Globalist", "Diplomatic", "Indifferent", "Patriotic", "Nationalist"],
        "Militancy":        ["Militarist", "Strategic"],
        "Diversity":        ["Homogenous", "Preservationist", "Indifferent", "Heterogeneous", "Multiculturalist"],
        "Secularity":       ["Apostate", "Secularist", "Indifferent", "Religious", "Devout"],
        "Justice":          ["Retributionist", "Punitive", "Indifferent", "Correctivist", "Rehabilitative"],
        "Natural-Balance":  ["Ecologist", "Naturalist", "Indifferent", "Productivist", "Industrialist"],
        "Government":       ["Democratic", "Republican", "Indifferent", "Oligarchic", "Autocratic"]
    },
    "Gang":{
        "Economy":          ["Indifferent", "Capitalist", "Free-Capitalist"],
        "Liberty":          ["Indifferent", "Libertarian", "Anarchist"],
        "Class":            ["Lower-Class", "Working-Class", "Populist", "Indifferent", "Middle-Class", "Aristocratic", "Plutocratic"],
        "Technology":       ["Technophobic", "Luddite", "Hesitant", "Indifferent", "Modernist", "TechnoOptimist","Transhumanist"],
        "Legality":         ["Arbitrarian", "Pragmatic", "Indifferent", "Proceduralist", "Legalist"],
        "Culture":          ["Traditionalist", "Conservative", "Indifferent", "Progressive", "Accelerationist"],
        "Diplomacy":        ["Patriotic", "Nationalist"],
        "Militancy":        ["Militarist", "Strategic"],
        "Diversity":        ["Homogenous", "Preservationist", "Indifferent", "Heterogeneous", "Multiculturalist"],
        "Secularity":       ["Apostate", "Secularist", "Indifferent", "Religious", "Devout"],
        "Justice":          ["Retributionist", "Punitive", "Indifferent"],
        "Natural-Balance":  ["Indifferent", "Productivist", "Industrialist"],
        "Government":       ["Oligarchic", "Autocratic"]
    },
    "Political":{
        "Economy":          ["Communist", "Socialist", "Indifferent", "Capitalist", "Free-Capitalist"],
        "Liberty":          ["Authoritarian", "Statist", "Indifferent", "Libertarian", "Anarchist"],
        "Class":            ["Lower-Class", "Working-Class", "Populist", "Indifferent", "Middle-Class", "Aristocratic", "Plutocratic"],
        "Technology":       ["Technophobic", "Luddite", "Hesitant", "Indifferent", "Modernist", "TechnoOptimist","Transhumanist"],
        "Legality":         ["Arbitrarian", "Pragmatic", "Indifferent", "Proceduralist", "Legalist"],
        "Culture":          ["Traditionalist", "Conservative", "Indifferent", "Progressive", "Accelerationist"],
        "Diplomacy":        ["Globalist", "Diplomatic", "Indifferent", "Patriotic", "Nationalist"],
        "Militancy":        ["Militarist", "Strategic", "Indifferent", "Diplomatic", "Pacifist"],
        "Diversity":        ["Homogenous", "Preservationist", "Indifferent", "Heterogeneous", "Multiculturalist"],
        "Secularity":       ["Apostate", "Secularist", "Indifferent", "Religious", "Devout"],
        "Justice":          ["Retributionist", "Punitive", "Indifferent", "Correctivist", "Rehabilitative"],
        "Natural-Balance":  ["Ecologist", "Naturalist", "Indifferent", "Productivist", "Industrialist"],
        "Government":       ["Democratic", "Republican", "Indifferent", "Oligarchic", "Autocratic"]
    }
}

FACTION_TYPES = [
    "Government",
    "Military",
    "Intelligence",
    "Religious",
    "Company",
    "Mercenaries",
    "Gang",
    "Political"
]

PERSONALITY_TRAIT_STRENGTH_DESCRIPTORS = [
    "barely",
    "slightly",
    "somewhat",
    "moderately",
    "fairly",
    "mostly",
    "very",
    "strongly",
    "staunchly",
    "extremely"
]

POLICY_BELIEF_STRENGTH_DESCRIPTORS = [
    "barely",
    "slightly",
    "somewhat",
    "moderately",
    "fairly",
    "mostly",
    "very",
    "strongly",
    "staunchly",
    "extremely"
]

POLICY_DESCRIPTIONS = {
    "Economy": {
        "Communist":"believes in a planned economy with no private ownership", 
        "Socialist":"believes in a managed market economy with significant government intervention", 
        "Interventionist":"believes in a market economy with some government intervention",
        "Indifferent":"", 
        "Capitalist":"believes in a market economy with some government intervention", 
        "Free-Capitalist":"believes in a free market economy without government intervention",
        "Hyper-Capitalist":"believes in a free market economy with minimal government intervention and a focus on profit maximization"
    },
    "Liberty": {
        "Totalitarian":"believes in a totalitarian state with no individual freedoms",
        "Authoritarian":"believes in an unapposed authority and solidarity of the state above the individual", 
        "Statist":"believes in a strong state and government control", 
        "Indifferent":"", 
        "Civil":"believes in the protection of individual rights and freedoms",
        "Libertarian":"believes in the freedom of the individual and minimal government intervention", 
        "Anarchist":"believes in the abolition of all forms of government and the state", 
    },
    "Class": {
        "Lower-Class":" believes in the rights and interests of the lower class",
        "Working-Class":" believes in the rights and interests of the working class",
        "Populist":" believes in the rights and interests of the common people",
        "Indifferent":"",
        "Middle-Class":" believes in the rights and interests of the middle class",
        "Aristocratic":" believes in the rights and interests of the aristocracy",
        "Plutocratic":" believes in the rights and interests of the wealthy elite",
    },
    "Technology": {
        "Technophobic":" believes that technology is dangerous and should be avoided",
        "Luddite":" believes that technology is harmful and should be resisted",
        "Hesitant":" believes that technology should be approached with caution and skepticism",
        "Indifferent":"",
        "Modernist":" believes that technology should be embraced and used to improve society",
        "TechnoOptimist":" believes that technology can solve all of society's problems and should be pursued at all costs",
        "Transhumanist":" believes in the use of technology to enhance human capabilities and transcend biological limitations",
    },
    "Legality": {
        "Disregardant":" believes that laws are arbitrary and should be disregarded",
        "Arbitrarian":" believes that laws are subjective and should be interpreted based on the situation",
        "Pragmatic":" believes that laws should be applied based on practical considerations",
        "Indifferent":"",
        "Regulatory":" believes in the regulation of society through laws and regulations",
        "Proceduralist":" believes in strict adherence to legal procedures and processes",
        "Legalist":" believes in the strict interpretation and application of laws without exception",
    },
    "Culture": {
        "Reactionary":"believes in returning to a previous state of culture and society",
        "Traditionalist":"believes in preserving their culture, traditions, and long term stability", 
        "Conservative":"believes in conserving their culture and traditions", 
        "Indifferent":"", 
        "Progressive":"believes in pushing the boundaries of culture and society forward", 
        "Accelerationist":"believes in the rapid advancement of culture and society regardless of the consequences", 
        "Post-Culturalist":"believes that culture is a construct and should be deconstructed",
    },
    "Diplomacy": {
        "Supranationalist":"believes in the integration of their faction into a larger supranational entity",
        "Globalist":"believes their faction should act as apart of a global community", 
        "Diplomatic":"believes that sometimes their own faction's interests must be set aside for the greater population", 
        "Indifferent":"", 
        "Patriotic":"believes in their faction's greatness", 
        "Nationalist":"believes in the superiority of their own faction", 
        "Isolationist":"believes in the isolation of their faction from the rest of the world",
    },
    "Militancy":{
        "Warhawk":"believes in the use of military force to achieve their faction's goals",
        "Militarist":"believes in military action as the best tool for resolving conflicts", 
        "Strategic":"believes in military action as a strategic tool for resolving conflicts when diplomacy fails to yield results", 
        "Indifferent":"", 
        "Conflict-Averse":"believes in avoiding military action and resolving conflicts through diplomacy",
        "Diplomatic":"believes in diplomacy and negotiating resolution of conflicts before military action", 
        "Pacifist":"believes in peaceful diplomacy and conflict resolution snubbing military action",

    },
    "Diversity": {
        "Ethnocentrist":"believes in the superiority of their own ethnicity",
        "Homogenous":"believes in a homogenous ethnic population", 
        "Preservationist":"believes in the preservation of their own ethnicity", 
        "Indifferent":"", 
        "Heterogeneous":"believes in some ethnic diversity", 
        "Multiculturalist":"believes in ethnic diversity", 
        "Inclusionist":"believes in the inclusion of all"
    },
    "Secularity": {
        "Atheist":"believes that religion is a delusion and should not play any role in society",
        "Apostate":"believes that religion should not play any role in society", 
        "Secularist":"believes in a secular society", 
        "Indifferent":"", 
        "Religious":"believes that religion should play a significant role in society", 
        "Devout":"believes that religion is should play a major role in society", 
        "Fundementalist":"believes that religion should play a dominant role in society and that its teachings should be strictly followed",
    },
    "Justice": {
        "Executionist":"believes in the death penalty for serious crimes",
        "Retributionist":"believes in judicial retribution", 
        "Punitive":"believes in punitive justice", 
        "Indifferent":"", 
        "Correctivist":"believes in corrective justice", 
        "Rehabilitative":"believes in rehabilitative justice", 
        "Abolitionist":"believes in the abolition of the justice system and its replacement with restorative justice practices",
    },
    "Natural-Balance": {
        "Eco-Extremist":"believes that the environment should be protected at all costs, even if it means sacrificing human interests",
        "Ecologist":"believes that the environment should be protected at the expense of industry", 
        "Naturalist":"believes in the natural balance of the environment", 
        "Indifferent":"", 
        "Utilitarian":"believes in the use of natural resources for the benefit of society",
        "Productivist":"believes in the use of natural resources for production", 
        "Industrialist":"believes in industrial production at the expense of the environment", 
    },
    "Government": {
        "Democratic":"believes in a government run by the collective will of the people", 
        "Republican":"believes in a representative government", 
        "Collectivist":"believes in a government run focus on the common good",
        "Indifferent":"", 
        "Oligarchic":"believes in a strong centralized authority", 
        "Autocratic":"believes in a centralized authority headed by a strong leader", 
        "Dictatorial":"believes in a government run by a single dictator with absolute power"
    }
}

POLICY_SCALES = {
    'name' : POLICY,
    'scales' : POLICY_SCALE,
    'descriptors' : POLICY_DESCRIPTIONS,
    'strength_descriptors' : POLICY_BELIEF_STRENGTH_DESCRIPTORS,
    'descriptors_buckets' : [3, 5, 8, 13, 21, 34],
    'center_index' : 3
}

PERSONALITY_SCALES = {
    'name' : PERSONALITY,
    'scales' : PERSONALITY_SCALE,
    'descriptors' : {},
    'strength_descriptors' : PERSONALITY_TRAIT_STRENGTH_DESCRIPTORS,
    'descriptors_buckets' : [3, 5, 8, 13, 21, 34],
    'center_index' : 3
}

SKILLS = {
    "Physical": [
        "Athletics",
        "Endurance",
        "Strength", 
        "Agility",
        "Balance",
        "Stealth",
        "Acrobatics",
    ],
    "Melee": [
        "Unarmed",
        "Blades",
        "Blunt Weapons",
        "Polearms",
        "Improvised",
        "Grappling",
        "Shield"
    ],
    "Ranged": [
        "Firearms",
        "Bows",
        "Throwing Weapons",
        "Artillery",
        "Energy Weapons",
    ],
    "Tactics": [
        "Close-Quarters Combat",
        "Formation Fighting",
        "Ambush",
        "Defense",
        "Urban Warfare",
        "Guerrilla Warfare",
        "Siege Warfare",
    ],
    "Survival": [
        "Wilderness Survival",
        "Urban Survival",
        "Foraging",
        "Tracking",
        "Hunting",
        "Navigation"
    ],
    "Environmental": [
        "Cold Weather Survival",
        "Hot Weather Survival",
        "Aquatic Survival",
        "Zero-Gravity Survival",
        "HAZMAT Survival"
    ],
    "Mechanics": [
        "Repair",
        "Mechanical Engineering",
        "Electrical Engineering",
        "Fabrication",
        "Tools",
        "Maintenance",
        "Architecture",
        "Reverse Physical Engineering"
    ],
    "Electronics": [
        "Electrical Systems",
        "Signal Systems",
        "Power Systems",
        "Circuitry",
        "Diagnostics & Troubleshooting",
        "Sensors",
        "Robotics",
        "Software Engineering",
        "Computer Engineering",
        "Reverse Software Engineering",
    ],
    "Crafting": [
        "Metalworking",
        "Woodworking",
        "Textiles",
        "Chemistry",
        "Tailoring",
    ],
    "Academics": [
        "History",
        "Geography",
        "Law",
        "Economics",
        "Politics",
        "Philosophy",
        "Theology",
        "Linguistics",
        "Sociology",
        "Psychology",
    ],
    "Science": [
        "Biology",
        "Chemistry",
        "Physics",
        "Environmental Science",
        "Computer Science",
        "Mathematics",
    ],
    "Medicine": [
        "First Aid",
        "Anatomy",
        "Disease Treatment",
        "Trauma Care",
        "Surgery",
        "Pharmacology",
        "Diagnostics",
        "Field Medicine",
        "PostHuman Medicine"
    ],
    "Analytics": [
        "Investigation",
        "Research",
        "Data Analysis",
        "Critical Thinking",
        "Systems Analysis",
        "Problem Solving",
        "Strategy",
        "Risk Assessment",
        "Pattern Recognition"
    ],
    "Communication": [
        "Persuasion",
        "Negotiation",
        "Intimidation",
        "Counseling",
        "Profiling",
        "Deception",
        "Leadership",
        "Oratory",
        "Interrogation",
        "Teaching",
        "Writing",
        "Etiquette",
        "Networking",
        "Leadership",
        "Command"
    ],
    "Infiltration": [
        "Lockpicking",
        "Bypass Systems",
        "Disguise",
        "Pickpocketing",
        "Surveillance",
        "Smuggling",
        "Forgery",
        "Sabotage",
        "Assassination",
        "Counter-Intelligence"
    ],
    "Vehicles": [
        "Ground Vehicles",
        "Aerial Vehicles",
        "Offroad Vehicles",
        "Convoy",
        "Watercraft",
        "Aircraft",
        "Spacecraft",
        "Navigation",
        "Piloting",
        "EVA Operations"
    ],
    "Culture": [
        "Art",
        "Music",
        "Storytelling",
        "Performance",
        "Dance",
        "Literature",
        "Customs",
        "Religion",
        "Fashion",
        "Cuisine",
    ],
    "Organization": [
        "Logistics",
        "Administration",
        "Governance",
        "Management",
    ],
    "Magic": [
        "Spellcasting",
        "Ritual",
        "Summoning",
        "Enchanting",
        "Alchemy",
        "Divination",
        "Herbalism",
        "Necromancy",
        "Psionics",
        "Telekinesis",
        "Telepathy",
        "Precognition",
        "Enchantment",
        "Illusion",
    ],
}

MADLIBS_SUFFIXES = {
    "Government":[
        "Republic",
        "Monarchy",
        "Kingdom",
        "Union",
        "State",
        "Federation",
        "Autocracy",
        "People's Republic",
        "States",
        "United"
    ],
    "Military":[
        "Battallion",
        "Specialists",
        "Group",
        "Task-Force",
        "Army",
        "Regiment",
        "Squad",
        "Company"
    ],
    "Intelligence":[
        "Agency",
        "Intelligence Agency",
        "Group",
        "Specialists",
        "Recon",
        "Bureau",
        "Initiative",
        "Task-Force",
        "Service",
        "Network",
        "Intelligence Department",
        "Information Agency",
        "Center",
        "Organization",
        "Intervention"
    ],
    "Institution":[
        "College",
        "Institute",
        "University",
        "Academy"
    ],
    "Religious":[
        "Church",
        "Cult"
    ],
    "Company":[
        "Communications",
        "Entertainment",
        "Consulting",
        "Solutions",
        "Contracting",
        "Consulting",
        "Group",
        "Company",
        "Holdings",
        "Ltd.",
        "Inc.",
        "Services",
        "Mfg.",
        "LLC.",
        "Co.",
        "Limited",
        "P.C.",
        "P.A."
    ],
    "Mercenaries":[
        "Consulting",
        "Outcomes",
        "Results",
        "Solutions",
        "Contracting",
        "Security",
        "Consulting",
        "Group",
        "Company",
        "Ltd.",
        "Inc.",
        "Services",
        "International"
    ],
    "Affinity":[
        "Club",
        "Group",
        "Association"
    ],
    "Gang":[
        "Gang",
        "Syndicate",
        "Group",
        "Cartel",
        "Ring"
    ],
    "Political":[
        "Bloc",
        "PAC"
    ]
}

MADLIBS_NOUNS = [
    "Alpha",
    "Beta",
    "Delta",
    "Zeta",
    "Omicron",
    "Omega",
    "Lambda",
    "Tau",
    "Gamma",
    "Sigma",
    "Eagle",
    "Wolf",
    "Spider",
    "Siege",
    "Sanguine",
    "Bear",
    "Hound",
    "Phoenix",
    "Dragon",
    "Lion",
    "Gorilla",
    "Rhino",
    "Storm",
    "Shadow",
    "Nocturn",
    "Prime",
    "Zeus",
    "Essence",
    "Banshee",
    "Specter",
    "Typhoon",
    "Pinnacle",
    "Odin",
    "Silver",
    "Platinum",
    "Titan",
    "Heart",
    "Karma",
    "Angel",
    "Demon",
    "Arcane",
    "Mystic",
    "Jupiter",
    "Mars",
    "Meridian",
    "Atlas",
    "Raptor",
    "Void",
    "Hurricane",
    "Harbor",
    "Cold",
    "Jet",
    "Global",
    "Green",
    "Red",
    "Blue",
    "Tap",
    "Soul",
    "Slick",
    "Omen",
    "Arm",
    "Revelation",
    "Twilight",
    "Quad",
    "Tri",
    "Saturn",
    "Ward",
    "Violet",
    "Minutemen",
    "Steel",
    "Granite",
    "Stone",
    "Slate",
    "First",
    "Federal",
    "Statement",
    "Macguffin",
    "United",
    "King",
    "Queen",
    "Sultan",
    "Atom",
    "Cellular",
    "Spruce",
    "Black",
    "Executive",
    "Admin"
]

HUMAN_BODY_METRICS = {
    "male":{
        "height": {
            'min': 1.55,
            'avg': 1.74,
            'max': 1.95,
            'stddev': 0.1
        },
        "weight": {
            "min": 60,
            "avg": 75,
            "max": 90,
            "stddev": 9
        },
        # todo ae: limbs
    },
    "female":{
        "height": {
            "min": 1.45,
            "avg": 1.61,
            "max": 1.8,
            "stddev": 0.1
        },
        "weight": {
            "min": 50,
            "avg": 65,
            "max": 75,
            "stddev": 10
        },
        # todo ae: limbs
    },
    "limbs": {
        'leg_height': 0.45,
        'torso_height': 0.35,
        'head_height': 0.15,
        'foot_height': 0.05,
        'arm_height': 0.45,
        'head_weight': 0.08,
        'leg_weight': 0.175,
        'torso_weight': 0.5,
        'arm_weight': 0.075,
        'hand_weight': 0.005,
        'foot_weight': 0.01,
    }
}